driver:
  name: terraform
  root_module_directory: test/fixtures/

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:  
    - name: local
      backend: local

platforms:
  - name: wc-deployment

suites:
  - name: default
