driver:
  name: terraform
  variable_files:
    - test.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform

  systems:
  
    - name: local
      backend: local
      controls:
        - remote

platforms:
  - name: wc-deployment

suites:
  - name: default
