driver:
  name: terraform
  root_module_directory: test/fixtures
  variable_files:
    - test/fixtures/test.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform

  systems:

    - name: remote
      backend: ssh
      hosts_output: redis_public_dns
      user: ubuntu
      sudo: true
      key_files:
        - test/assets/kitchen-wc-redis-test
      controls:
        - local
    
    - name: local
      backend: local
      controls:
        - remote

platforms:
  - name: redis

suites:
  - name: default
