driver:
  name: terraform
  root_module_directory: test/fixtures
  variable_files:
    - test/fixtures/test.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform

  systems:

    - name: local
      backend: local
      controls:
        - remote

    - name: remote
      backend: ssh
      hosts_output: webcounter_public_dns
      user: ubuntu
      key_files:
        - test/assets/kitchen-wc-test
      controls:
        - local

platforms:
  - name: webcounter

suites:
  - name: default
