driver:
  name: terraform
  # The test fixture Terraform configuration is configured to be the Terraform
  # root module
  root_module_directory: test/fixtures
  variables:
    ami_id: "ami-039b608d6700512d0"
    redis_address: "10.10.10.10"
    redis_password: "testRedisPassw0rd"

provisioner:
  name: terraform

verifier:
  name: terraform

  systems:

    - name: local
      backend: local
      controls:
        - remote

    - name: remote
      backend: ssh
      hosts_output: webcounter_public_dns
      user: ubuntu
      key_files:
        - test/assets/kitchen-wc-test
      controls:
        - local

platforms:
  - name: webcounter

suites:
  - name: default
